### PR TITLE
Google Maps example

### LINKED ISSUE #21: Google Maps in a screenshot
When I have Google Maps in the hierarchy the screenshot shows just a black surface. Here is the screenshot taken with Telescope. 

telescope-2015-09-08-100034

I think #13 would fix this for > Lollipop devices.

### PR DESCRIPTION
**Pull request by tasomaniac**
Example tab with Google Maps canvas screenshot is added.

Google works so hard for people to use `MapFragment`. Docs say that if we are using `MapView` we have to call 6 lifecycle callbacks manually. Which I am not doing here. I didn't take time to do it cleanly. For demo purposes I think it is fine. What do you think?

For maps to work, we need API key. So I included a `debug.keystore` into the source code with a API key taken from Google Developers Cloud Console. It is not the best practice to put this API key into source control but for demo purposes I think it is fine. You may want to change that.

Here is a screenshot taken in the sample using Telescope:
telescope-2016-02-18-132308

Here is one from an emulator w/o Google Play Services:

screenshot_20160218-132224

Fixes #21

### CODE REVIEW

**Comment by tasomaniac** [comment]
2nd screenshot is not taken with Telescope. 

In the first one, shadow below the `TabLayout` is not shown. Do you think it is related to my code or does it happen in all canvas screenshots?

**Comment by mattprecious** [comment]
Yeah, shadows aren't captured using the canvas method. Not related to your code at all!

**Comment by mattprecious** [comment]
I don't really care about the missing callbacks or the API key best practices. This is a Telescope sample, not MapView 101 :smile: 

Thanks for submitting this! I'll take a closer look over the weekend hopefully.

**Comment by mattprecious** [comment]
This is awesome! It works great. I made some formatting changes and merged manually. Thanks again!

**Comment by tasomaniac** [comment]
Thank you for merging it. I hope it would be a useful example for others.

**Pull request closed without merging**
