### PR TITLE
Fix crash in sample code

### PR DESCRIPTION
**Pull request by kkamaraj**
Changed the image format to RGBA_8888 as RGBX format is crashing in
Motorola Nexus 6 running 5.1.1

### CODE REVIEW

**Comment by JakeWharton** [comment]
This was explicitly changed in https://github.com/mattprecious/telescope/commit/c56d6fecacc26f560d87070775c61398b436c6b9. Sounds like we need to do some kind of feature detection here.

**Comment by mattprecious** [comment]
Ugh...

**Comment by mattprecious** [comment]
I don't know what to do here. I don't know if/how we can know which format is going to be given to us.

**Comment by NightlyNexus** [comment]
What happens when using `PixelFormat.RGB_888`?

**Comment by mattprecious** [comment]
If I recall correctly, both `RGBA` and `RGBX` fail to convert to `RGB`.

**Comment by kkamaraj** [comment]
If we cannot know which format we are going to get can we use captureCanvasScreenshot() for API level 21 and below?

**Comment by mattprecious** [comment]
The latest release (1.5) uses canvas screenshots in all cases: https://github.com/mattprecious/telescope/tree/1.5.0

This system screenshot feature was recently added to master and I guess there's still some kinks to work out. I don't know if changing back to `RGBA` is the right solution since it crashes on devices that only support `RGBX`.

**Comment by kkamaraj** [comment]
Thank you for the clarification. I get it why I do not see a crash in my project. 
We use 1.5 for our project. We had an issue with HTC device where 3 finger touch was not recognized for some reason. So wanted to add some logs into onInterceptTouchEvents() call to get actual touch count for 3 finger. It appears that HTC device is sending touch count as 2 for 3 finger touch as well. I was testing sample app from master where I found the crash did not realize that it is not 1.5 release.

I accept that changing the format to RGBA is not a solution. Looking through the ImageReader/MediaProjection API to find a viable solution.Looking forward to give my contribution for this project.

**Comment by mattprecious** [comment]
Seeing as the only thing I know of that fails for `RGBA_8888` is the genymotion emulator, and `RGBX_8888` apparently crashes on a real phone, I'm going to merge this. #30 turns the crash into a graceful fallback, so I'm fine shipping this and seeing what happens.

**Pull request merged**
