### PR TITLE
Reduce FileProvider visibility

### PR DESCRIPTION
**Pull request by mattprecious**

### CODE REVIEW

**Comment by mattprecious** [comment]
Hmm... do I actually want to do this? What about when I have a custom `Lens` in my app and I want to create a `content://` URI for the screenshot? Have to think about this some more.

**Comment by JakeWharton** [comment]
I was going to comment on the original PR but it has to be public for Android to instantiate it.

**Comment by mattprecious** [comment]
I'll probably rename it then and make it easier to use in custom lenses.

**Comment by JakeWharton** [comment]
You might want to package scope the copied FileProvider and then dedicate a
public API subclass so that transitioning back to the support-v4 one (when
it gets fixed) becomes just an import change and file deletion.

**Pull request closed without merging**
