### PR TITLE
Fix travis

### PR DESCRIPTION
**Pull request by tasomaniac**
Fix travis build. Build tools was updated but not the travis config.

### CODE REVIEW

**Comment by mattprecious** [comment]
Travis isn't doing so hot today...

**Comment by tasomaniac** [comment]
The initialization of the new container based infrastructure is much faster. It sometimes don't work on big projects though. Did you intentionally not enable it? I can update the PR to use the new container based infrastructure.

**Comment by mattprecious** [comment]
I just discovered that. Yeah, add the `sudo: false` to this PR and I'll merge!

**Comment by tasomaniac** [comment]
Copied and pasted from  https://github.com/JakeWharton/Telecine/blob/master/.travis.yml :smile_cat: 
I can squash the 2 commits if you want to.

**Comment by mattprecious** [comment]
Thanks!

**Comment by tasomaniac** [comment]
:+1:

**Pull request merged**
